
services:
  postgres:
    image: postgres:15
    container_name: tocloc-db
    environment:
      POSTGRES_DB: toclocdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user1234567
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d toclocdb"]
      interval: 5s
      timeout: 5s
      retries: 15

  app:
    build: .
    container_name: tocloc-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/toclocdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: user1234567
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
    ports:
      - "8080:3000"

volumes:
  postgres_data: